### ISSUE TITLE
cannot import name 'calculate_offset' from 'homeassistant.components.calendar' error

### ISSUE THREAD

**Issue by true-bluey** [tykeal/homeassistant-rental-control#89]
After upgrading to 2022.4.0 I installed Rental Control. I'm getting error below on startup of HAss

`Unable to prepare setup for platform rental_control.calendar: Platform not found (cannot import name 'calculate_offset' from 'homeassistant.components.calendar' (/usr/src/homeassistant/homeassistant/components/calendar/__init__.py)).`

There's reference to a breaking change in a couple of other posts, but I can't see anything in release notes on this.

**Comment by tykeal** [comment]
I just released v0.6.0 which resolves this error. Closed with #90
